CREATE TABLE IF NOT EXISTS "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"first_name" varchar(100) NOT NULL,
	"last_name" varchar(100) NOT NULL,
	"email" varchar NOT NULL,
	"country_code" varchar(10),
	"phone_no" varchar(15),
	"password" varchar(100),
	"wallet_address" varchar(255),
	"wallet_private_key" varchar(255),
	"is_google" boolean DEFAULT false NOT NULL,
	"image" text,
	"created_at" date DEFAULT now(),
	"updated_at" date DEFAULT now(),
	"created_by" integer,
	"updated_by" integer,
	"is_disabled" boolean DEFAULT false NOT NULL,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"email_verified" boolean DEFAULT false NOT NULL,
	"city" varchar(100),
	"state" varchar(100),
	"country" varchar(100),
	"refresh_token" varchar(1000),
	"dob" date,
	"gender" varchar(50),
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
